import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './global_style.scss'
import Header from './components/header/Header'
import SideBar from './components/sidebar/SideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <main>
                <Header/>
                <section>
                  <aside>
                    <SideBar/>
                  </aside>
                  <div>{children}</div>
                </section>
                <footer>footer</footer>
            </main> 
        </body>
    </html>
  )
}
